name: Build and Test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

      - name: Grant execute permission for Gradle wrappers
        run: |
          chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew runAllTests

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: /home/runner/work/tui-challenge/tui-challenge/data/build/reports/tests/testDebugUnitTest/index.html