name: Build and Test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

      - name: Grant execute permission for Gradle wrappers
        run: |
          chmod +x app/gradlew
          chmod +x domain/gradlew
          chmod +x data/gradlew

      - name: Build and run tests (app module)
        run: ./app/gradlew :app:clean :app:test

      - name: Build and run tests (domain module)
        run: ./domain/gradlew :domain:clean :domain:test

      - name: Build and run tests (data module)
        run: ./data/gradlew :data:clean :data:test