name: Build and Test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

      - name: Grant execute permission for Gradle wrappers
        run: |
          chmod +x ./gradlew

      - name: Build and run tests in data module
        run: ./gradlew :data:testDebugUnitTest --info

      - name: Build and run tests in domain module
        run: ./gradlew :domain:testDebugUnitTest --info

      - name: Build and run tests in app module
        run: ./gradlew :app:testDebugUnitTes --info

